### ISSUE TITLE
Compiling Errors

### ISSUE THREAD

**Issue by xehn1337** [90XA/Valorant-External#1]
![image](https://user-images.githubusercontent.com/100049731/183910862-8e5b14e9-1993-4336-839e-376f3e14d38e.png)

**Comment by xehn1337** [comment]
nvm fixed it

**Comment by ThotBreakerrr** [comment]
how did u fixed it my guy?

**Comment by ThotBreakerrr** [comment]
I'm starting to go crazy with all these errors
